// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgsQjog8n48aCPvpup-L8rmklOoPbXws',
    appId: '1:286715298714:web:248594be6151160dcbf023',
    messagingSenderId: '286715298714',
    projectId: 'volapp-5b3b1',
    authDomain: 'volapp-5b3b1.firebaseapp.com',
    storageBucket: 'volapp-5b3b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIL6MXGtfi5cLUVKgWzWs3VhYMX1C5kS4',
    appId: '1:286715298714:android:2a353dc960876b90cbf023',
    messagingSenderId: '286715298714',
    projectId: 'volapp-5b3b1',
    storageBucket: 'volapp-5b3b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSHqBSsj6cAEgmyl9LeSgOZzJ4A-JN00',
    appId: '1:286715298714:ios:4b4869caec856760cbf023',
    messagingSenderId: '286715298714',
    projectId: 'volapp-5b3b1',
    storageBucket: 'volapp-5b3b1.appspot.com',
    iosBundleId: 'com.example.volsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWSHqBSsj6cAEgmyl9LeSgOZzJ4A-JN00',
    appId: '1:286715298714:ios:42bd2d9847c3ee4fcbf023',
    messagingSenderId: '286715298714',
    projectId: 'volapp-5b3b1',
    storageBucket: 'volapp-5b3b1.appspot.com',
    iosBundleId: 'com.example.volsapp.RunnerTests',
  );
}
